#!/bin/bash

output=$([[ "$(pacmd stat | awk -F ': ' '/^Default sink name: /{print $2}')" != "alsa_output.pci-0000_00_1f.3.analog-stereo" ]] && echo ' ' || echo ' ')

volume=$(pacmd list-sinks | awk '/^\s+name: /{indefault = $2 == "<'$(pacmd stat | awk -F": " '/^Default sink name: /{print $2}')'>"}/^\s+volume: / && indefault {print $5; exit}')

echo "$output$volume"
